config/routes.rb
Rails.application.routes.draw do
  resources :foods
  resources :controllers
  get 'foods/show'
  get 'foods/edit'
  get 'static_pages/home'
  get "static_pages/pantry"
  get "static_pages/food_form"
  resources :users
  root 'static_pages#home'
  get 'foods#index' => "static_pages#pantry"
  get 'foods#edit' => "static_pages#food_form"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/controller.rb
class Controller < ApplicationRecord
end

app/models/food.rb
class Food < ApplicationRecord
  #belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :foods
  has_secure_password
  before_save { self.email = email.downcase }
  enum role: [:pantry, :supplier, :individual, :admin]
  after_initialize :set_default_role, :if => :new_record?
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }
  def set_default_role
    self.role ||= :pantry
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def fp_hello
    render html: "This is FullPlate. Hello"
  end


end

app/controllers/controllers_controller.rb
class ControllersController < ApplicationController
  before_action :set_controller, only: [:show, :edit, :update, :destroy]

  # GET /controllers
  # GET /controllers.json
  def index
    @controllers = Controller.all
  end

  # GET /controllers/1
  # GET /controllers/1.json
  def show
  end

  # GET /controllers/new
  def new
    @controller = Controller.new
  end

  # GET /controllers/1/edit
  def edit
  end

  # POST /controllers
  # POST /controllers.json
  def create
    @controller = Controller.new(controller_params)

    respond_to do |format|
      if @controller.save
        format.html { redirect_to @controller, notice: 'Controller was successfully created.' }
        format.json { render :show, status: :created, location: @controller }
      else
        format.html { render :new }
        format.json { render json: @controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /controllers/1
  # PATCH/PUT /controllers/1.json
  def update
    respond_to do |format|
      if @controller.update(controller_params)
        format.html { redirect_to @controller, notice: 'Controller was successfully updated.' }
        format.json { render :show, status: :ok, location: @controller }
      else
        format.html { render :edit }
        format.json { render json: @controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /controllers/1
  # DELETE /controllers/1.json
  def destroy
    @controller.destroy
    respond_to do |format|
      format.html { redirect_to controllers_url, notice: 'Controller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_controller
      @controller = Controller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def controller_params
      params.require(:controller).permit(:User, :name, :email, :address, :zip)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  
  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show

  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :PLU, :durability, :diet_protected, :weight, :size)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        redirect_to '/'
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        redirect_to '/signup'
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_params
      params.require(:user).permit(:name, :email, :zip,:address,:password,
                                   :password_confirmation)
    end
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/controllers/_form.html.erb
<%= form_with(model: controller, local: true) do |form| %>
  <% if controller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(controller.errors.count, "error") %> prohibited this controller from being saved:</h2>

      <ul>
      <% controller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :User %>
    <%= form.text_field :User %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.number_field :zip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/controllers/edit.html.erb
<h1>Editing Controller</h1>

<%= render 'form', controller: @controller %>

<%= link_to 'Show', @controller %> |
<%= link_to 'Back', controllers_path %>

app/views/controllers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Controllers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @controllers.each do |controller| %>
      <tr>
        <td><%= controller.User %></td>
        <td><%= controller.name %></td>
        <td><%= controller.email %></td>
        <td><%= controller.address %></td>
        <td><%= controller.zip %></td>
        <td><%= link_to 'Show', controller %></td>
        <td><%= link_to 'Edit', edit_controller_path(controller) %></td>
        <td><%= link_to 'Destroy', controller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Controller', new_controller_path %>

app/views/controllers/new.html.erb
<h1>New Controller</h1>

<%= render 'form', controller: @controller %>

<%= link_to 'Back', controllers_path %>

app/views/controllers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @controller.User %>
</p>

<p>
  <strong>Name:</strong>
  <%= @controller.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @controller.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @controller.address %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @controller.zip %>
</p>

<%= link_to 'Edit', edit_controller_path(@controller) %> |
<%= link_to 'Back', controllers_path %>

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :PLU %>
    <%= form.number_field :PLU %>
  </div>

  <div class="field">
    <%= form.label :durability %>
    <%= form.text_field :durability %>
  </div>

  <div class="field">
    <%= form.label :diet_protected %>
    <%= form.text_field :diet_protected %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Plu</th>
      <th>Durability</th>
      <th>Diet protected</th>
      <th>Weight</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.PLU %></td>
        <td><%= food.durability %></td>
        <td><%= food.diet_protected %></td>
        <td><%= food.weight %></td>
        <td><%= food.size %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Plu:</strong>
  <%= @food.PLU %>
</p>

<p>
  <strong>Durability:</strong>
  <%= @food.durability %>
</p>

<p>
  <strong>Diet protected:</strong>
  <%= @food.diet_protected %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @food.weight %>
</p>

<p>
  <strong>Size:</strong>
  <%= @food.size %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullPlate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= yield %>
  </body>
</html>

app/views/static_pages/food_form.html.erb
<% provide(:title, "food_form") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>food_form | Connecting people and food</title>
  </head>
  <body>
    <h1>Full Plate</h1>
    <p>This is the food_form.</p>

    <%= render 'form', food: @food %>

    <%= link_to 'Show', @food %> |
    <%= link_to 'Back', foods_path %>

    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>home | Connecting people and food</title>
  </head>
  <body>
    <h1>Full Plate</h1>
    <p>This is home.</p>
    <%= yield %>
  </body>
</html>

app/views/static_pages/pantry.html.erb
<% provide(:title, "pantry") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>pantry | Connecting people and food</title>
  </head>
  <body>
    <h1>Full Plate</h1>
    <p>This is the pantry.</p>
    <table>
    <tr>

    </tr>
    </table>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>